#!/bin/bash
# Update llms.txt with current documentation structure
# This script is run by GitHub Actions after documentation changes
#
# llms.txt is served publicly at ${BASE_URL}/llms.txt, so every link it emits
# must be a deployed Starlight URL. Repository-relative paths do not resolve
# for the LLM clients that consume this file.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONTENT_DIR="$PROJECT_ROOT/docs/src/content/docs"
LLMS_FILE="$PROJECT_ROOT/docs/public/llms.txt"
BASE_URL="https://rshade.github.io/finfocus"

if [ ! -d "$CONTENT_DIR" ]; then
    echo "ERROR: content directory not found: $CONTENT_DIR" >&2
    exit 1
fi

echo "Updating documentation index in $LLMS_FILE..."

# Convert a content file path into its deployed Starlight URL.
# Starlight lowercases slugs and drops the extension; index becomes the root.
to_url() {
    local rel="$1" slug
    slug="$(printf '%s' "${rel%.*}" | tr '[:upper:]' '[:lower:]')"
    [ "$slug" = "index" ] && slug=""
    printf '%s/%s' "$BASE_URL" "${slug:+$slug/}"
}

# Read the frontmatter title, falling back to the slug when absent.
to_title() {
    local file="$1" title
    title="$(sed -n '2,/^---$/{s/^title:[[:space:]]*//p}' "$file" | head -1)"
    title="${title%\"}"; title="${title#\"}"
    title="${title%\'}"; title="${title#\'}"
    printf '%s' "$title"
}

TEMP_FILE=$(mktemp)
trap 'rm -f "$TEMP_FILE"' EXIT

cat > "$TEMP_FILE" << EOF
# FinFocus Documentation Index (LLM-Friendly)

This file provides a machine-readable index of all FinFocus documentation.
Use this as context when answering questions about FinFocus.

All links are deployed documentation URLs and resolve directly.

## Quick Navigation

### For End Users
- Getting Started: $BASE_URL/getting-started/quickstart/
- Installation: $BASE_URL/getting-started/installation/
- CLI Reference: $BASE_URL/reference/cli-commands/
- Troubleshooting: $BASE_URL/support/troubleshooting/
- FAQ: $BASE_URL/support/faq/

### For Plugin Developers
- Plugin Development Guide: $BASE_URL/plugins/plugin-development/
- Plugin SDK Reference: $BASE_URL/plugins/plugin-sdk/
- Vantage Plugin Example: $BASE_URL/plugins/vantage/readme/
- Plugin Examples: $BASE_URL/plugins/plugin-examples/
- Vantage Setup: $BASE_URL/plugins/vantage/setup/

### For Software Architects
- System Architecture: $BASE_URL/architecture/system-overview/
- Plugin Protocol: $BASE_URL/architecture/plugin-protocol/
- Cost Calculation: $BASE_URL/architecture/cost-calculation/
- Deployment Guide: $BASE_URL/deployment/deployment/
- Security Best Practices: $BASE_URL/deployment/security/

### For Business/Product
- Business Value: $BASE_URL/guides/business-value/
- Comparison: $BASE_URL/guides/comparison/
- Roadmap: $BASE_URL/architecture/roadmap/

---

## Complete Documentation Map

EOF

doc_count=0
while IFS= read -r file; do
    rel="${file#"$CONTENT_DIR"/}"
    url="$(to_url "$rel")"
    title="$(to_title "$file")"
    [ -n "$title" ] || title="${rel%.*}"
    echo "- [$title]($url)" >> "$TEMP_FILE"
    doc_count=$((doc_count + 1))
done < <(find "$CONTENT_DIR" -type f \( -name "*.md" -o -name "*.mdx" \) | sort)

cat >> "$TEMP_FILE" << 'EOF'

## Key Concepts

### FinFocus
CLI tool for calculating cloud infrastructure costs from Pulumi definitions.

**Three Cost Types:**
1. **Projected Costs** - Estimated costs from Pulumi preview
2. **Actual Costs** - Historical costs from cloud provider APIs
3. **Cost Changes** - Difference between current and previous states

### Resource
Representation of cloud infrastructure element.

### Plugin
External service integration for cost data.

### Cost Aggregation
Combining costs from multiple resources and/or plugins.

---

## Documentation Maintenance

### Regular Updates
- Monthly: Review llms.txt, update plugin status
- Quarterly: Update architecture diagrams, verify examples
- On Release: Update version, new features, roadmap
- On Plugin Status Change: Update plugin docs and status

### Quality Standards
- All code examples tested
- Links validated monthly (automated)
- Screenshots updated with UI changes
- API reference stays in sync with code

---

## How to Use This File

### For AI Assistants
- Use this as context when answering questions about FinFocus
- Reference specific docs by their deployed URLs
- Point users to the most relevant documentation

### For Documentation Maintainers
- Regenerate with: ./scripts/update-llms-txt.sh
- Update when creating new documentation
- Validate that llms.txt matches actual file structure

---

EOF

cat >> "$TEMP_FILE" << EOF
**Last Updated:** $(date -u +"%Y-%m-%d")
**This file is generated by scripts/update-llms-txt.sh.**
EOF

mv "$TEMP_FILE" "$LLMS_FILE"
trap - EXIT

echo "✓ Documentation index updated successfully"
echo "✓ Indexed $doc_count documentation files"
